name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: []  # No dependencies, runs first

    steps:
      - name: Setup repository
        uses: actions/checkout@v4.1.1

      - name: Cache gradle
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Use JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run unit tests
        run: bash ./gradlew test --stacktrace
  
  apk:
    name: Build & Distribute APK
    runs-on: ubuntu-latest
    needs: test  # Depends on the successful completion of the "test" job

    steps:
      - name: Setup repository
        uses: actions/checkout@v4.1.1

      - name: Use JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build debug APK
        run: |
          if [[ ${{ needs.test.outputs.result == 'success' }} ]]; then
            echo "Tests passed, proceeding with building APK..."
            bash ./gradlew assembleDebug --stacktrace
          else
            echo "Tests failed, skipping APK build and distribution."
          fi
        shell: bash

      - name: Create APK artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
        # Only upload artifact if the previous step succeeded (tests passed)
        if: ${{ success() }}

      - name: Distribute APK to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1.3.4
        with:
          appName: mohsinraza-10P/Android-CI-CD
          token: ${{ secrets.APPCENTER_SECRET }}
          group: Testers
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: true
          debug: false
        # Only distribute if the previous step succeeded (artifact uploaded)
        if: ${{ success() }}